In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,2,6,2,6,9,8,5])
arr1

array([1, 2, 3, 4, 2, 6, 2, 6, 9, 8, 5])

In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)

(11,)


In [4]:
print(arr1.size)

11


In [5]:
arr2= np.array([[1,2,3, 7,6,13],[3,4,5,7,9,2],[3,5,2,6,4,9]])
arr2

array([[ 1,  2,  3,  7,  6, 13],
       [ 3,  4,  5,  7,  9,  2],
       [ 3,  5,  2,  6,  4,  9]])

In [6]:
print(arr2.shape)
print(arr2.size)

(3, 6)
18


In [7]:
print(arr2[1][2])
print(arr2[1,2])

5
5


In [8]:
arr3 = np.array(["China", "USA", "Mexico"])
arr3

array(['China', 'USA', 'Mexico'], dtype='<U6')

In [9]:
#this creates a i-dim array from 0-20 in increment of 2
arrR= np.arange(0,20,2)

In [10]:
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#This creates a 1-dim array of possibble 20 elements of common factor from 0-10
arrL = np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [12]:
arr = np.random.rand(10)
#This creates a 1-dim array of 10 random nums btw o and 1
arr

array([0.06744252, 0.51386435, 0.7453096 , 0.48285829, 0.17637268,
       0.08076004, 0.55299694, 0.49583666, 0.94930603, 0.92557528])

In [13]:
arr = np.random.rand(2,3)
#this creates a 2*3 dim array of random elements btw 0 and 1
arr

array([[0.70460568, 0.709855  , 0.52768873],
       [0.24156448, 0.77838471, 0.83095085]])

In [14]:
print(np.zeros(10))
print(np.zeros((2,3)))      

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
arr = [[0,1,2], [3,4,5]]
print(np.repeat(arr, 3))
#This rep each element three times before moving to another element, 1-dim arr

[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [18]:
print(np.tile(arr, 3))
#This reps each row three times on a row before moving to the next row

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]


In [19]:
ident_mat = np.eye(3)
#This creates an identity matrix
ident_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
print(np.diag([1,2]))
#this creates a diagonal matrix with diag entries 1 and 2

[[1 0]
 [0 2]]


In [21]:
arr = np.random.rand(5,5)
arr
# this creates a 5*5 arr with rndm nums btw 0 and 1

array([[0.35265743, 0.08002647, 0.02443888, 0.2891631 , 0.33540417],
       [0.92533901, 0.30742997, 0.03266457, 0.53361278, 0.14121485],
       [0.0502054 , 0.39671219, 0.6332585 , 0.42411349, 0.22890365],
       [0.46656163, 0.05448536, 0.74737002, 0.82583671, 0.32925521],
       [0.386096  , 0.07235391, 0.93409613, 0.78835224, 0.72754177]])

In [22]:
np.diag(arr)


array([0.35265743, 0.30742997, 0.6332585 , 0.82583671, 0.72754177])

In [23]:
arr.ndim

2

In [24]:
np.random.randint(-10,10,4)
#4 random integer btw -10 and 10

array([  7,   8, -10,   1])

In [25]:
arr*2

array([[0.70531486, 0.16005295, 0.04887776, 0.5783262 , 0.67080835],
       [1.85067801, 0.61485994, 0.06532914, 1.06722556, 0.28242969],
       [0.1004108 , 0.79342437, 1.266517  , 0.84822697, 0.4578073 ],
       [0.93312327, 0.10897071, 1.49474005, 1.65167342, 0.65851042],
       [0.77219201, 0.14470783, 1.86819226, 1.57670448, 1.45508355]])

In [26]:
np.exp(arr)

array([[1.42284363, 1.08331575, 1.02473996, 1.3353095 , 1.39850551],
       [2.52272333, 1.35992557, 1.03320391, 1.70508128, 1.15167205],
       [1.05148705, 1.48692791, 1.88373875, 1.52823502, 1.2572209 ],
       [1.59450227, 1.05599701, 2.11143967, 2.28379083, 1.38993253],
       [1.47122591, 1.07503575, 2.54491215, 2.19976874, 2.06998586]])

In [27]:
np.log10(arr)

array([[-0.45264696, -1.09676632, -1.61191867, -0.53885713, -0.47443154],
       [-0.03369913, -0.5122538 , -1.48592307, -0.27277378, -0.85011964],
       [-1.29924958, -0.40152446, -0.19841897, -0.37251792, -0.64034728],
       [-0.33109098, -1.2637202 , -0.12646432, -0.08310582, -0.48246734],
       [-0.41330469, -1.14053797, -0.02960843, -0.10327969, -0.13814207]])

In [28]:
np.log(arr)

array([[-1.04225815, -2.52539777, -3.7115799 , -1.2407644 , -1.09241899],
       [-0.07759512, -1.17950797, -3.42146431, -0.62808483, -1.95747281],
       [-2.99163271, -0.92454424, -0.45687657, -0.8577542 , -1.47445411],
       [-0.76236515, -2.9098233 , -0.29119487, -0.19135821, -1.11092212],
       [-0.95166922, -2.62618572, -0.06817592, -0.23781029, -0.31808386]])

In [29]:
np.tan(arr)

array([[0.36804295, 0.08019775, 0.02444375, 0.29750159, 0.34857433],
       [1.32791354, 0.31749609, 0.03267619, 0.59078037, 0.14216108],
       [0.05024762, 0.41892306, 0.73411738, 0.45151548, 0.2329872 ],
       [0.50364786, 0.05453934, 0.926696  , 1.08433338, 0.34169291],
       [0.40649857, 0.07248044, 1.35239793, 1.00592567, 0.89050028]])

In [30]:
np.sin(arr)

array([[0.34539291, 0.07994108, 0.02443645, 0.28515017, 0.32915085],
       [0.79882474, 0.3026101 , 0.03265876, 0.50864717, 0.14074597],
       [0.05018431, 0.38638797, 0.59177458, 0.41151297, 0.22690991],
       [0.44981808, 0.0544584 , 0.67971208, 0.73511528, 0.32333834],
       [0.37657469, 0.0722908 , 0.80406202, 0.70919254, 0.66503582]])

In [31]:
np.sum(arr)

10.087093440897647

In [32]:
arr


array([[0.35265743, 0.08002647, 0.02443888, 0.2891631 , 0.33540417],
       [0.92533901, 0.30742997, 0.03266457, 0.53361278, 0.14121485],
       [0.0502054 , 0.39671219, 0.6332585 , 0.42411349, 0.22890365],
       [0.46656163, 0.05448536, 0.74737002, 0.82583671, 0.32925521],
       [0.386096  , 0.07235391, 0.93409613, 0.78835224, 0.72754177]])

In [33]:
np.sum(arr, axis=0)

array([2.18085947, 0.9110079 , 2.37182811, 2.86107831, 1.76231965])

In [34]:
np.sum(arr, axis=1)

array([1.08169006, 1.94026117, 1.73319322, 2.42350893, 2.90844006])

In [35]:
arr2

array([[ 1,  2,  3,  7,  6, 13],
       [ 3,  4,  5,  7,  9,  2],
       [ 3,  5,  2,  6,  4,  9]])

In [36]:
np.min(arr2)

1

In [37]:
np.min(arr2, axis=0)

array([1, 2, 2, 6, 4, 2])

In [38]:
np.min(arr2, axis=1)

array([1, 2, 2])

In [39]:
np.std(arr2)

3.0087321475668896

In [40]:
np.var(arr2)

9.052469135802468

In [41]:
arr2[1:,3:5]

array([[7, 9],
       [6, 4]])

In [42]:
arr2

array([[ 1,  2,  3,  7,  6, 13],
       [ 3,  4,  5,  7,  9,  2],
       [ 3,  5,  2,  6,  4,  9]])

In [43]:
np.sort(arr2)


array([[ 1,  2,  3,  6,  7, 13],
       [ 2,  3,  4,  5,  7,  9],
       [ 2,  3,  4,  5,  6,  9]])

In [44]:
np.sort(arr2, axis=1)

array([[ 1,  2,  3,  6,  7, 13],
       [ 2,  3,  4,  5,  7,  9],
       [ 2,  3,  4,  5,  6,  9]])

In [45]:
arr2.T

array([[ 1,  3,  3],
       [ 2,  4,  5],
       [ 3,  5,  2],
       [ 7,  7,  6],
       [ 6,  9,  4],
       [13,  2,  9]])

In [46]:
arr2[1:,1:4].T


array([[4, 5],
       [5, 2],
       [7, 6]])

In [47]:
arr2

array([[ 1,  2,  3,  7,  6, 13],
       [ 3,  4,  5,  7,  9,  2],
       [ 3,  5,  2,  6,  4,  9]])

In [48]:
#This turn the n-dimensionaal array into 1-dimensional array
arr2.flatten()

array([ 1,  2,  3,  7,  6, 13,  3,  4,  5,  7,  9,  2,  3,  5,  2,  6,  4,
        9])

In [49]:
arr2

array([[ 1,  2,  3,  7,  6, 13],
       [ 3,  4,  5,  7,  9,  2],
       [ 3,  5,  2,  6,  4,  9]])

In [50]:
arr1


array([1, 2, 3, 4, 2, 6, 2, 6, 9, 8, 5])

In [51]:
nwarr = np.insert(arr1, -1, 7)
nwarr
#it replaces the second to the last element with 7

array([1, 2, 3, 4, 2, 6, 2, 6, 9, 8, 7, 5])

In [52]:
nwarr2= np.append(nwarr, [2,7])
nwarr2

array([1, 2, 3, 4, 2, 6, 2, 6, 9, 8, 7, 5, 2, 7])

In [53]:
nwarr3 = np.delete(nwarr2, [1,4,7])
nwarr3

array([1, 3, 4, 6, 2, 9, 8, 7, 5, 2, 7])

In [54]:
arr5 = [[1,2,3,4], [5,6,7,8]]
arr6 = [[9,10,11,12],[13,14,15,16]]
arr_cat = np.concatenate((arr5,arr6), axis=0)
print(arr_cat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [55]:
arr_cat1 = np.concatenate((arr5,arr6), axis=1)
print(arr_cat1)

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [56]:
catv = np.vstack((arr5, arr6))
catv

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
cath = np.hstack((arr5, arr6))
cath

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [58]:
arr1

array([1, 2, 3, 4, 2, 6, 2, 6, 9, 8, 5])

In [59]:
np.unique(arr1)

array([1, 2, 3, 4, 5, 6, 8, 9])

In [60]:
uniques, counts = np.unique(arr1, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6 8 9]
[1 3 1 1 1 2 1 1]


In [61]:
#intersection, differentiation, neither
arr8 = [1,2,3,4,5]
arr9 = [3,4,5,6,7]
print(np.intersect1d(arr8, arr9))
print(np.union1d(arr8, arr9))
print(np.setdiff1d(arr8, arr9))
print(np.setxor1d(arr8, arr9))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]
